name: Trigger Vercel deploy (prod)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  trigger-vercel-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel deploy
        run: |
          curl -X POST ${{ secrets.VERCEL_DEPLOY_LINK_PROD }}

  update-search-records:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger search records update in steampipe.io
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.G_PERSONAL_ACCESS_TOKEN }}
          repository: turbot/steampipe.io
          event-type: update-search-records
